### ISSUE TITLE
Targets should not get variables from other targets

### ISSUE THREAD

**Issue by zedshaw** [dexy/dexy#128]
I have a .rst file like this:

```
{{ args }}
```

And a yaml like this:

```
pages:
    - .rst|jinja|rst:
        - rst:
            template: template.html
            language: python

ruby-pages:
    - .rst|jinja|rst:
        - rst:
            template: template.html
            language: ruby
```

So I can do conditional builds and set the language I want in the output of my book.  Problem is, if I run:

  dexy -r -target pages

Then it'll write out:

  {'rst': {'language': 'python', 'template': 'template.html'}, 'environment': {}}

But then if I do:

  dexy -r -target ruby-pages

It still spits out "language": "python" and not ruby.  However if I run it a bunch of times it will randomly decide that the language is now ruby, and I can't switch it back to python.

Ultimately I'd like to just be able to say what language is being selected in my .rst|jinja templates for the output, so if this isn't how I do it let me know.
