### ISSUE TITLE
Dexy could not find an input document, but says it exists !

### ISSUE THREAD

**Issue by Orabig** [dexy/dexy#144]
Here is my dexy output : 

ERROR while running docsrc/README.md|jinja: No document named '**shell-autodoc.sh**'
is available as an input to 'docsrc/README.md|jinja'.
There are 11 input documents available, their keys have been written to dexy's log.
Did you mean '**shell-autodoc.sh**'?

However, "shell-autodoc.sh" seems to be declared in my dexy.yaml : 

```
docsrc/README.md|jinja:
   - perl/check_test.pl|idio
   - shell-autodoc.sh:
      - contents: "./check_fs.pl --autodoc"
   - shell-autodoc.sh|sh:
      - contents: "perl ./perl/check_test.pl --autodoc"
      - perl/check_test.pl
      - perl/lib/Nagios/Autoconf.pm
   - shell-autoconf.sh:
      - contents: "./check_fs.pl -H 192.168.1.2 -w 60 -c 75 --autoconf"
   - shell-autoconf.sh|sh:
      - contents: "perl ./perl/check_test.pl -H 192.168.1.2 -w 60 -c 75 --autoconf"
      - perl/check_test.pl
      - perl/lib/Nagios/Autoconf.pm
   - shell-autoconf-command.sh:
      - contents: "./check_fs.pl -H 192.168.1.2 -w 60 -c 75 --autoconf --commandline"
   - shell-autoconf-command.sh|sh:
      - contents: "perl ./perl/check_test.pl -H 192.168.1.2 -w 60 -c 75 --autoconf --commandline"
      - perl/check_test.pl
      - perl/lib/Nagios/Autoconf.pm
   - shell-version.sh|pyg:
      - contents: "perl ./perl/check_test.pl --version"
   - shell-version.sh|sh:
      - contents: "perl ./perl/check_test.pl --version"
      - perl/check_test.pl
      - perl/lib/Nagios/Autoconf.pm
```

And here are the logs : 

```
dexy - INFO - starting logging for dexy
dexy - INFO - using config file 'dexy.yaml'
dexy - INFO - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja: running...
dexy - INFO - (state:running) 2ab22d6ab6c137e0921a83c9b7f733cc doc:perl/check_test.pl|idio: using cache for self and any children
dexy - INFO - (state:running) 2ed34296a5a401404f0eddd16eb7ea32 doc:shell-autodoc.sh: running...
dexy - INFO - (state:running) f635b23922e5c51f9123452622ffa93d doc:shell-autodoc.sh|sh: running...
dexy - INFO - (state:running) 1cd7efe54546548628297753f0c614f6 doc:perl/check_test.pl: using cache for self and any children
dexy - INFO - (state:running) 6481df9378878720a292e492b2495a55 doc:perl/lib/Nagios/Autoconf.pm: using cache for self and any children
dexy - INFO - (state:running) 416cc0ae71101689c5b6ea6399ce5dd1 doc:shell-autoconf.sh: running...
dexy - INFO - (state:running) 70476354e84b16e038a67e89fd127385 doc:shell-autoconf.sh|sh: running...
dexy - INFO - (state:running) 1cd7efe54546548628297753f0c614f6 doc:perl/check_test.pl: using cache for self and any children
dexy - INFO - (state:running) 6481df9378878720a292e492b2495a55 doc:perl/lib/Nagios/Autoconf.pm: using cache for self and any children
dexy - INFO - (state:running) fe0437ae7c2051a9b5dc57aec7ec23ed doc:shell-autoconf-command.sh: running...
dexy - INFO - (state:running) 0c1a1e76e7a9db62642d657dd35df3ea doc:shell-autoconf-command.sh|sh: running...
dexy - INFO - (state:running) 1cd7efe54546548628297753f0c614f6 doc:perl/check_test.pl: using cache for self and any children
dexy - INFO - (state:running) 6481df9378878720a292e492b2495a55 doc:perl/lib/Nagios/Autoconf.pm: using cache for self and any children
dexy - INFO - (state:running) 94e3e0e00c18e8ee4e71d34c32d62e25 doc:shell-version.sh|pyg: running...
dexy - INFO - (state:running) 649e3f4e5663b6f5d416bb6b94a01848 doc:shell-version.sh|sh: running...
dexy - INFO - (state:running) 1cd7efe54546548628297753f0c614f6 doc:perl/check_test.pl: using cache for self and any children
dexy - INFO - (state:running) 6481df9378878720a292e492b2495a55 doc:perl/lib/Nagios/Autoconf.pm: using cache for self and any children
dexy - WARNING - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja: Listing documents which are available:
dexy - WARNING - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja:   perl/check_test.pl
dexy - WARNING - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja:   perl/check_test.pl|idio
dexy - WARNING - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja:   perl/lib/Nagios/Autoconf.pm
dexy - WARNING - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja:   shell-autoconf-command.sh
dexy - WARNING - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja:   shell-autoconf-command.sh|sh
dexy - WARNING - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja:   shell-autoconf.sh
dexy - WARNING - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja:   shell-autoconf.sh|sh
dexy - WARNING - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja:   shell-autodoc.sh
dexy - WARNING - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja:   shell-autodoc.sh|sh
dexy - WARNING - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja:   shell-version.sh|pyg
dexy - WARNING - (state:running) 2e9c65b83c16e18b200ab152a66b829d doc:docsrc/README.md|jinja:   shell-version.sh|sh
dexy - WARNING - ERROR while running docsrc/README.md|jinja: No document named 'shell-autodoc.sh'
is available as an input to 'docsrc/README.md|jinja'.
There are 11 input documents available, their keys have been written to dexy's log.
Did you mean 'shell-autodoc.sh'?
```

**Comment by Orabig** [comment]
Ok, I found out something very weird : 

This works : 

```
README.md|jinja:
   - shell-autodoc.sh:
      - contents: "./check_fs.pl --autodoc"
   - shell-autodoc.sh|sh:
      - contents: "perl ./perl/check_test.pl --autodoc"
      - perl/check_test.pl
      - perl/lib/Nagios/Autoconf.pm
```

but not this : 

```
docsrc/README.md|jinja:
   - shell-autodoc.sh:
      - contents: "./check_fs.pl --autodoc"
   - shell-autodoc.sh|sh:
      - contents: "perl ./perl/check_test.pl --autodoc"
      - perl/check_test.pl
      - perl/lib/Nagios/Autoconf.pm
```

The only difference is the path to README.md source file.
Of course, both files are totally identical.
